name: Test

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'release/**'
  push:
    branches:
      - main

jobs:
  test:
    name: Jest Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: cache-node-modules
        uses: actions/cache@v4
        id: node_modules_cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: npm-install
        if: ${{ steps.node_modules_cache.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: run-tests-changed
        if: github.event_name == 'pull_request'
        run: npx jest --changedSince=origin/main --passWithNoTests

      - name: run-tests-all
        if: github.event_name == 'push'
        run: npx jest

  coverage:
    name: Coverage Report
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: cache-node-modules
        uses: actions/cache@v4
        id: node_modules_cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: npm-install
        if: ${{ steps.node_modules_cache.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: run-coverage
        run: npx jest --coverage --ci --json --testLocationInResults --outputFile=report.json || true

      - name: coverage-report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          skip-step: all
          annotations: none
          coverage-file: report.json
          base-coverage-file: report.json
